mariOS: source/cmsis_os.c File Reference
cmsis_os.c File Reference
#include "cmsis_os.h"
Functions
osStatus osKernelInitialize (void)
osStatus osKernelStart (void)
uint32_t osKernelSysTick (void)
osThreadId osThreadCreate (const osThreadDef_t *thread_def, void *argument)
osThreadId osThreadGetId (void)
osStatus osThreadTerminate (osThreadId thread_id)
osStatus osThreadYield (void)
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
osPriority osThreadGetPriority (osThreadId thread_id)
osStatus osDelay (uint32_t millisec)
Function Documentation
osDelay()
osStatus osDelay (uint32_t millisec)
References mariOS_delay().
 {
         mariOS_delay(millisec);
         return osOK;
 }
osKernelInitialize()
osStatus osKernelInitialize (void)
References mariOS_init().
{
         mariOS_init();
 }
osKernelStart()
osStatus osKernelStart (void)
References MARIOS_CONFIG_SYSTICK_FREQ, and mariOS_start().
 {
   mariOS_start(MARIOS_CONFIG_SYSTICK_FREQ);
   return osOK;
 }
osKernelSysTick()
uint32_t osKernelSysTick (void)
References marios_systick_handler().
 {
         marios_systick_handler();
 }
osThreadCreate()
osThreadId osThreadCreate (const osThreadDef_t * thread_def, void * argument)
References mariOS_task_init().
 {
         return mariOS_task_init(thread_def->pthread, thread_def->stacksize, thread_def->priority, thread_def->period);
 }
osThreadGetId()
osThreadId osThreadGetId (void)
 {
         return NULL;
 }
osThreadGetPriority()
osPriority osThreadGetPriority (osThreadId thread_id)
 {
   return osPriorityError;
 }
osThreadSetPriority()
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
 {
   return osErrorOS;
 }
osThreadTerminate()
osStatus osThreadTerminate (osThreadId thread_id)
 {
   return osErrorOS;
 }
osThreadYield()
osStatus osThreadYield (void)
References mariOS_task_yield().
 {
         mariOS_task_yield();
   return osOK;
 }