mariOS: include/mariOS.h File Reference
mariOS.h File Reference
Header file of main functionalities of mariOS. This file provides the mariOS task status enum, the definition of the task control block and public function for end users to manage the RTOS.
#include <mariOS_config.h>
#include "port.h"
#include <string.h>
#include <stdlib.h>
Data Structures
struct mariOS_task_control_block_t
This struct defines the mariOS task control block. It contains the task stack pointer, the function pointer to the task implementation, the task status, the last time it has been scheduled as active, the number of ticks that the mariOS system tick has to reach to switch its status from MARIOS_TASK_STATUS_WAIT to MARIOS_TASK_STATUS_READY.
Macros
#define mariOS_Task(taskname) static void taskname(void)
#define mariOS_begin_periodic do{
#define mariOS_end_periodic
Typedefs
typedef uint32_t mariOS_stack_t
typedef uint16_t mariOS_task_id_t
typedef uint8_t mariOS_priority
Enumerations
enum mariOS_task_status_t { MARIOS_TASK_STATUS_READY = 0, MARIOS_TASK_STATUS_ACTIVE = 1, MARIOS_TASK_STATUS_WAIT = -1, MARIOS_TASK_STATUS_SUSPEND = 2 }
Functions
void mariOS_init (void)
This function initialize the mariOS_tasks_list struct and populate it with the first task of the system, namely the idle one. For this reason, idle takes the threadID 0.
mariOS_task_id_t mariOS_task_init (void(*handler)(void), uint32_t stack_size, mariOS_priority priority, uint32_t period)
This function initialize a new entry in the tasks list. Actually, mariOS defines a task as a C function with no input/output parameters (properly, non returning/cyclic).The stack size has to be statically determined, taking into account the number of nesting function calling and related static-allocated data (which belongs to the task's stack).
int mariOS_start (uint32_t systick_ticks)
This function makes mariOS started, meant that the system's timer has to\ be configured accordingly to the mariOS defined sytick and the first task\ (the idle one) has to be loaded. Depending on the system target, some other configurations must be provided, especially those related to the interrupt controller, interrupt priority and additional driver configuration.
void mariOS_scheduler (void)
This function implements the mariOS's scheduler. The main aim is to get the current active task status to MARIOS_TASK_STATUS_READY (mariOS_current_task), pick a task from the mariOS's tasks list and assign it to the mariOS_next_task, which is then set as MARIOS_TASK_STATUS_READY.
void mariOS_task_yield (void)
This function implements the task yield, hence it gives to a task the possibility of a self-preemption for letting the scheduler pick another task. Hence, first, the function must call the scheduler, then it forces the system to call the yield, which forces the PendSV_Handler() ISR whenever the scheduler picks a task different to the current active one.
void mariOS_delay (uint32_t ticks)
This function allows to switch the task status from MARIOS_TASK_STATUS_ACTIVE to the MARIOS_TASK_STATUS_WAIT. In particular, the function must record the time (expressed in mariOS ticks) on which the task status has to be switch to MARIOS_TASK_STATUS_READY. Until the task status is MARIOS_TASK_STATUS_WAIT, the scheduler cannot execute (mariOS does not admit task status transition from MARIOS_TASK_STATUS_WAIT to MARIOS_TASK_STATUS_ACTIVE).
void mariOS_systick_handler (void)
This function represents the core of mariOS. As a common implementation along RTOS projects, the systick handler must take care about main duties of the RTOS that must be performed periodically. A basic one comprehend the mariOS_ticks incrementing, the verification of which tasks that have the status MARIOS_TASK_STATUS_WAIT must be switched as MARIOS_TASK_STATUS_READY and, finally, the scheduler calling.
mariOS_task_id_t get_current_task_id (void)
This accessory function returns the mariOS_task_id of the current active task.
void set_current_task_status (mariOS_task_status_t status)
This accessory function configure the status of the current active task.
void set_task_status (mariOS_task_id_t task_id, mariOS_task_status_t status)
This accessory function configure the status of the a task.
mariOS_task_status_t get_current_task_status (void)
This accessory function returns the status of the current active task.
uint32_t get_current_task_period (void)
This accessory function returns the period of the current active task.
mariOS_task_status_t get_task_status (mariOS_task_id_t task_id)
This accessory function returns the status of a given task.
uint8_t get_idle_percentage (void)
This function returns, in percentage, the idle of the processor.
Detailed Description
Header file of main functionalities of mariOS. This file provides the mariOS task status enum, the definition of the task control block and public function for end users to manage the RTOS.
Author
Mario Barbareschi mario.nosp@m..bar.nosp@m.bares.nosp@m.chi@.nosp@m.unina.nosp@m..it
Version
V1.1
Date
10-July-2018
Attention
Copyright (C) 2018 Mario Barbareschi
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
mariOS_begin_periodic
#define mariOS_begin_periodic do{
mariOS_end_periodic
#define mariOS_end_periodic
Value:
mariOS_active_after(get_current_task_period());\
                                                        }while (1)
mariOS_Task
#define mariOS_Task (taskname) static void taskname(void)
Typedef Documentation
mariOS_priority
typedef uint8_t mariOS_priority
mariOS_stack_t
typedef uint32_t mariOS_stack_t
mariOS_task_id_t
typedef uint16_t mariOS_task_id_t
Enumeration Type Documentation
mariOS_task_status_t
enum mariOS_task_status_t
The mariOS_task_status_t is the enumerative type that mariOS exploits for implemeting the scheduler. Actually, mariOS handles four different task status.
MARIOS_TASK_STATUS_READY indicates that a task is ready to be scheduled, hence the scheduling algorithm can take it into consideration.
MARIOS_TASK_STATUS_ACTIVE indicates that a taks is currently executing. As one can figure out, one and only one task a time takes the active status.
MARIOS_TASK_STATUS_WAIT means that a task performed the mariOS_delay function for some ticks which have not yet been elapsing. In this status, a task cannot be scheduled as active.
MARIOS_TASK_STATUS_SUSPEND means that a task voluntary performed a yield due to a resource contest, such as sending/receiving to/from a queue. In this status, a task cannot be scheduled as active.
Enumerator
MARIOS_TASK_STATUS_READY
Task is ready to be scheduled as active
MARIOS_TASK_STATUS_ACTIVE
Task is currently being executed
MARIOS_TASK_STATUS_WAIT
Task invoked the delay function
MARIOS_TASK_STATUS_SUSPEND
Task invoked yield because a resource is busy or it does not exist yet
 {
         MARIOS_TASK_STATUS_READY = 0,
         MARIOS_TASK_STATUS_ACTIVE = 1,
         MARIOS_TASK_STATUS_WAIT = -1,
         MARIOS_TASK_STATUS_SUSPEND = 2
 } mariOS_task_status_t;
Function Documentation
get_current_task_id()
mariOS_task_id_t get_current_task_id (void)
This accessory function returns the mariOS_task_id of the current active task.
Parameters
None
Return values
mariOS_task_id of the current active task
 {
         return mariOS_tasks_list.current_active_task;
 }
get_current_task_period()
uint32_t get_current_task_period (void)
This accessory function returns the period of the current active task.
Parameters
None
Returns
mariOS_task_status of the current active task
 {
         return mariOS_tasks_list.tasks[mariOS_tasks_list.current_active_task].period;
 }
get_current_task_status()
mariOS_task_status_t get_current_task_status (void)
This accessory function returns the status of the current active task.
Warning
Currently, mariOS admits one and only one status when the task is running, namely MARIOS_TASK_STATUS_ACTIVE. However, future extensions may plan more than one active status.
Parameters
None
Returns
mariOS_task_status of the current active task
References get_task_status().
 {
         return get_task_status(mariOS_tasks_list.current_active_task);
 }
get_idle_percentage()
uint8_t get_idle_percentage (void)
This function returns, in percentage, the idle of the processor.
Parameters
None
Returns
the idle of the processor, between 0 and 100
References marios_idle_value.
{
         return marios_idle_value;
 }
get_task_status()
mariOS_task_status_t get_task_status (mariOS_task_id_t task_id)
This accessory function returns the status of a given task.
Parameters
[in] task_id is the ID of the task
Returns
mariOS_task_status of the task_id task
 {
         return mariOS_tasks_list.tasks[task_id].status;
 }
mariOS_delay()
void mariOS_delay (uint32_t ticks)
This function allows to switch the task status from MARIOS_TASK_STATUS_ACTIVE to the MARIOS_TASK_STATUS_WAIT. In particular, the function must record the time (expressed in mariOS ticks) on which the task status has to be switch to MARIOS_TASK_STATUS_READY. Until the task status is MARIOS_TASK_STATUS_WAIT, the scheduler cannot execute (mariOS does not admit task status transition from MARIOS_TASK_STATUS_WAIT to MARIOS_TASK_STATUS_ACTIVE).
Once the task status transition from MARIOS_TASK_STATUS_ACTIVE to MARIOS_TASK_STATUS_WAIT completed, the function calls mariOS_task_yield to call the scheduler and perform a context switch.
Parameters
[in] ticks represents the mariOS ticks that the scheduler must wait before taking into account the task when it is called.
Return values
None
References mariOS_active_after(), and MARIOS_CONFIG_SYSTICK_FREQ_DIV.
{
         mariOS_active_after(MARIOS_CONFIG_SYSTICK_FREQ_DIV*millisec/1000);
 }
mariOS_init()
void mariOS_init (void)
This function initialize the mariOS_tasks_list struct and populate it with the first task of the system, namely the idle one. For this reason, idle takes the threadID 0.
Parameters
None
Return values
None
Current idle process implementation does not need a lot of space, even though its minimum size depends on the target architecture.
 {
         memset(&mariOS_tasks_list, 0, sizeof(mariOS_tasks_list));
         mariOS_ticks = 0;
         mariOS_task_init(mariOS_idle, MARIOS_IDLE_TASK_STACK, 0, 0);
 }
mariOS_scheduler()
void mariOS_scheduler (void)
This function implements the mariOS's scheduler. The main aim is to get the current active task status to MARIOS_TASK_STATUS_READY (mariOS_current_task), pick a task from the mariOS's tasks list and assign it to the mariOS_next_task, which is then set as MARIOS_TASK_STATUS_READY.
Currently, the scheduler implementation is just a round robin, hence the scheduler picks the task next to the current one in the mariOS tasks list. Obviously, a more sophisticated implementation is feasible, but maybe the mariOS_task_control_block_t should be enriched with further information.
Most important aspect, which does not depend on specific implementation of scheduler, is the existance of the mariOS_idle task. Indded, each time the scheduler is not able to determine a task to be executed, it should pick the mariOS_idle task instead. In other words, the mariOS_idle task is the least priority task of the system, matching the general meaing of the idle task.
Parameters
None
Return values
None
Retrieve the current active task
If it is active, namely it has been set neither in wait nor suspend, its status must be changed in ready
Now, we need to pick the next task:
 {
         mariOS_curr_task = &mariOS_tasks_list.tasks[mariOS_tasks_list.current_active_task];
         if(MARIOS_TASK_STATUS_ACTIVE == mariOS_curr_task->status)
                 mariOS_curr_task->status = MARIOS_TASK_STATUS_READY;
         MARIOS_SCHEDULER_FUNCTION();
         mariOS_next_task = &mariOS_tasks_list.tasks[mariOS_tasks_list.current_active_task];
         mariOS_next_task->status = MARIOS_TASK_STATUS_ACTIVE;
 }
mariOS_start()
int mariOS_start (uint32_t systick_ticks)
This function makes mariOS started, meant that the system's timer has to\ be configured accordingly to the mariOS defined sytick and the first task\ (the idle one) has to be loaded. Depending on the system target, some other configurations must be provided, especially those related to the interrupt controller, interrupt priority and additional driver configuration.
Note
Even though this function is declared to return an integer value, it should never return since the first task has to be scheduled before reaching the end of the function.
Parameters
[in] systick_ticks is the number of last_active_time's ticks between two interruption events
Return values
None. The function is declared for returning an integer, but this function should never return
This point should be never reached
References configureSystick().
 {
         configureSystick(systick_ticks);
         /* Start the first task: should be the first non-idle */
         mariOS_curr_task = &mariOS_tasks_list.tasks[mariOS_tasks_list.current_active_task];
         loadFirstTask();
         return 0;
 }
mariOS_systick_handler()
void mariOS_systick_handler (void)
This function represents the core of mariOS. As a common implementation along RTOS projects, the systick handler must take care about main duties of the RTOS that must be performed periodically. A basic one comprehend the mariOS_ticks incrementing, the verification of which tasks that have the status MARIOS_TASK_STATUS_WAIT must be switched as MARIOS_TASK_STATUS_READY and, finally, the scheduler calling.
Parameters
None
Return values
None
mariOS_task_init()
mariOS_task_id_t mariOS_task_init (void(*)(void) handler, uint32_t stack_size, mariOS_priority priority, uint32_t period)
This function initialize a new entry in the tasks list. Actually, mariOS defines a task as a C function with no input/output parameters (properly, non returning/cyclic).The stack size has to be statically determined, taking into account the number of nesting function calling and related static-allocated data (which belongs to the task's stack).
Status of each created task is set to MARIOS_TASK_STATUS_READY, meant that the scheduler may pick it to be the current executed task, setting it to the status MARIOS_TASK_STATUS_ACTIVE.
MariOS tasks are defined with a priority, which can be potentially used by the scheduling algorithm
Parameters
[in] handler is the function pointer
[in] stack_size decides the size of the task's stack
[in] priority is the priority value assigned to the task
[in] period is the period value (in milliseconds) assigned to the task
Return values
None
The taskID of tasks starts from 0, while mariOS_idle does not have any ID, even though its index is 0
 {
         if (mariOS_tasks_list.size >= MARIOS_CONFIG_MAX_TASKS-1)
                 return -1;
         /* Initialize the task structure and set SP to the top of the stack
            minus 16 words (64 bytes) to leave space for storing 16 registers: */
         mariOS_task_control_block_t *p_task = &mariOS_tasks_list.tasks[mariOS_tasks_list.size];
         p_task->handler = handler;
         if(MARIOS_MINIMUM_TASK_STACK_SIZE >= stack_size)
                 stack_size = MARIOS_MINIMUM_TASK_STACK_SIZE;
         mariOS_stack_t *p_stack = malloc(stack_size*sizeof(mariOS_stack_t));
         p_task->sp = (uint32_t)(p_stack+stack_size-16);
         p_task->status = MARIOS_TASK_STATUS_READY;
         p_task->wait_ticks = 0;
         p_task->priority = priority;
         p_task->period = MARIOS_CONFIG_SYSTICK_FREQ_DIV*period/1000;
         /* Here some special registers are defined and they  will be restored on exception return, namely:
            - XPSR: Default value (0x01000000)
            - PC: Point to the handler function
            - LR: Point to a function to be called when the handler returns */
         p_stack[stack_size-1] = 0x01000000;
         p_stack[stack_size-2] = (uint32_t)handler;
         p_stack[stack_size-3] = (uint32_t) &task_completion;
         mariOS_tasks_list.size++;
         return (mariOS_tasks_list.size-1);
 }
mariOS_task_yield()
void mariOS_task_yield (void)
This function implements the task yield, hence it gives to a task the possibility of a self-preemption for letting the scheduler pick another task. Hence, first, the function must call the scheduler, then it forces the system to call the yield, which forces the PendSV_Handler() ISR whenever the scheduler picks a task different to the current active one.
Parameters
None
Return values
None
Actually, we are triggering the activation of the PendSV_Handler()
References mariOS_task_control_block_t::last_active_time, mariOS_scheduler(), mariOS_ticks, and yield().
 {
         mariOS_scheduler();
         mariOS_next_task->last_active_time = mariOS_ticks;
         if(mariOS_next_task != mariOS_curr_task)
         {
                 yield();
         }
 }
set_current_task_status()
void set_current_task_status (mariOS_task_status_t status)
This accessory function configure the status of the current active task.
Parameters
[in] status is the new status of current active task
Return values
None
References set_task_status().
 {
         set_task_status(mariOS_tasks_list.current_active_task, status);
 }
set_task_status()
void set_task_status (mariOS_task_id_t task_id, mariOS_task_status_t status)
This accessory function configure the status of the a task.
Parameters
[in] task_id is the id of the task to modify
[in] status is the new status of current active task
Return values
None
 {
         mariOS_tasks_list.tasks[task_id].status = status;
 }