mariOS: source/queue.c File Reference
queue.c File Reference
Implementation file of mariOS queue. It just contains implementation of function declared in the corresponding header file.
#include "queue.h"
Functions
mariOS_queue * createQueue (unsigned int size)
The function initialize a mariOS_queue structure with a specified size.
mariOS_queue_op_status_t enqueue (mariOS_queue *queue, int8_t *msg, unsigned int msg_size, mariOS_blocking_queue_op_t blocking)
The enqueue function tries to put a message onto the specified \ queue. It takes in input a message and its size (in bytes) and enqueue the message if the queue is not locked for writing operation and if the queue has enough space to contain the message. Whenever these two conditions are not met, the behavior of the function depends on the value of passed.
mariOS_queue_op_status_t dequeue (mariOS_queue *queue, int8_t *msg, unsigned int msg_size, mariOS_blocking_queue_op_t blocking)
The dequeue function tries to pull a message from the specified queue. It takes in input the size of the message to read and the area on which store it. The message is read from the queue if it is not locked for reading operations and if the queue contains at least the amount of requested data. Whenever these two conditions are not met, the behavior of the function depends on the value of ::marios_blocking_queue_op_t passed.
void reset_queue (mariOS_queue *queue)
The function restore the queue in a pristine state.
Detailed Description
Implementation file of mariOS queue. It just contains implementation of function declared in the corresponding header file.
Author
Mario Barbareschi mario.nosp@m..bar.nosp@m.bares.nosp@m.chi@.nosp@m.unina.nosp@m..it
Version
V1.0
Date
11-July-2018
Attention
Copyright (C) 2018 Mario Barbareschi
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
createQueue()
mariOS_queue* createQueue (unsigned int size)
The function initialize a mariOS_queue structure with a specified size.
Parameters
[in] size is the queue size in bytes
Returns
pointer to the mariOS_queue created
we assume to create an unlocked queue
reset_queue() is used to perform remaining initializations
References MARIOS_QUEUE_UNLOCKED, queue_t::queueMemory, reset_queue(), queue_t::rLock, size, queue_t::size, and queue_t::wLock.
 {
         mariOS_queue* queue = (mariOS_queue*) malloc(sizeof(mariOS_queue));
         queue->size = size;
         queue->queueMemory = malloc(size);
         queue->rLock = MARIOS_QUEUE_UNLOCKED;
         queue->wLock = MARIOS_QUEUE_UNLOCKED;
         reset_queue(queue);
         return queue;
 }
dequeue()
mariOS_queue_op_status_t dequeue (mariOS_queue * queue, int8_t * msg, unsigned int size, mariOS_blocking_queue_op_t blocking)
The dequeue function tries to pull a message from the specified queue. It takes in input the size of the message to read and the area on which store it. The message is read from the queue if it is not locked for reading operations and if the queue contains at least the amount of requested data. Whenever these two conditions are not met, the behavior of the function depends on the value of ::marios_blocking_queue_op_t passed.
If MARIOS_BLOCKING_QUEUE_OP is passed and the queue does not contain the message to dequeue, the function suspend the task that will be eventually resumed once the queue has been enqueued by another task. Otherwise, if the queue is just locked for reading operation, the task is simply preempted and will be eventually rescheduled.
If MARIOS_NONBLOCKING_QUEUE_OP is passed, the function will return error conditions related to the condition that impedes the dequeue. Indeed, two possible conditions may happen:
MARIOS_QUEUE_BUSY_OP, which indicates that the queue is blocked for reading operations.
MARIOS_QUEUE_EMPTY_OP, which indicates that the queue does not contain requested message.
Conversely, if the dequeue succeeds, no matter if blocking or not, the function returns MARIOS_QUEUE_SUCCESS_OP.
Parameters
[in,out] queue is the mariOS_queue handler from which the message should be dequeued
[out] msg is the pointer on which the message will be stored
[in] size is the message size (in bytes)
[in] blocking specifies if the dequeue is blocking or not
Returns
operation success or failure
the yield call has no effect since it is invoked inside a critical section! It will eventually have effect once the critical section ends.
Since we are executing a non-blocking dequeue, we return from this function signaling that the queue is empty (MARIOS_QUEUE_EMPTY_OP). Before returning, we must exit from the critical section as well as we must unlock the reading operations on the queue
the yield call has no effect since it is invoked inside a critical section! It will eventually have effect once the critical section ends.
Since we are executing a non-blocking dequeue, we return from this function signaling that the queue is busy (MARIOS_QUEUE_BUSY_OP). Before returning, we must exit from the critical section.
Reaching this point implies that the while loop terminates upon the condition receivedFlag != 0, meaning that we successfully dequeue a message
References enter_critical_section(), exit_critical_sction(), queue_t::freeMemory, get_current_task_id(), MARIOS_BLOCKING_QUEUE_OP, MARIOS_CONFIG_MAX_TASKS, MARIOS_QUEUE_BUSY_OP, MARIOS_QUEUE_EMPTY_OP, MARIOS_QUEUE_LOCKED, MARIOS_QUEUE_SUCCESS_OP, MARIOS_QUEUE_UNLOCKED, MARIOS_TASK_STATUS_READY, MARIOS_TASK_STATUS_SUSPEND, mariOS_task_yield(), queue_t::queueMemory, queue_t::rLock, set_current_task_status(), set_task_status(), size, queue_t::size, queue_t::tail, queue_t::tasks_waiting_to_receive, queue_t::tasks_waiting_to_send, and queue_t::wLock.
 {
         int receivedFlag = 0;
         while(0 == receivedFlag) //This flag will be set once the writing is achieved
         {
                 enter_critical_section();
                 {
                         if(MARIOS_QUEUE_UNLOCKED == queue->rLock)
{
                                 queue->rLock = MARIOS_QUEUE_LOCKED;
                                 if(msg_size > (queue->size - queue->freeMemory)) //Check whether the queue is containing at least one msg
{
                                         if(MARIOS_BLOCKING_QUEUE_OP == blocking)
{
                                                 queue->tasks_waiting_to_receive[get_current_task_id()] = 1;
                                                 set_current_task_status(MARIOS_TASK_STATUS_SUSPEND);
                                                 mariOS_task_yield();
                                         }
                                         else
{
                                                 queue->wLock = MARIOS_QUEUE_UNLOCKED;
                                                 exit_critical_sction();
                                                 return MARIOS_QUEUE_EMPTY_OP;
                                         }
                                 }
                                 else //There is at least one msg
{
                                         if(queue->tail+msg_size <= queue->size) //If the message is stored along the queue
{
                                                 memcpy(msg, queue->queueMemory+queue->tail,msg_size);
                                                 queue->tail += msg_size;
                                         }
                                         else //We need to split the copy
{
                                                 memcpy(msg, queue->queueMemory+queue->tail, queue->size-queue->tail);
                                                 memcpy(msg+queue->size-queue->tail, queue->queueMemory, msg_size-(queue->size-queue->tail));
                                                 queue->tail = msg_size-(queue->size-queue->tail); //The tail just point to the next non-free region
                                         }
                                         queue->freeMemory += msg_size;
                                         //Let's make awaken suspended tasks
                                         int i;
                                         for(i = 0; i < MARIOS_CONFIG_MAX_TASKS; i++)
                                                 if(1 == queue->tasks_waiting_to_send[i])
{
                                                         set_task_status(i, MARIOS_TASK_STATUS_READY);
                                                         queue->tasks_waiting_to_send[i] = 0;
                                                 }
                                         receivedFlag = 1;
                                 }
                                 queue->rLock = MARIOS_QUEUE_UNLOCKED;
                         }
                         else //The queue is just locked for receiving
{
                                 if(MARIOS_BLOCKING_QUEUE_OP == blocking)
{
                                         mariOS_task_yield();
                                 }
                                 else
{
                                         exit_critical_sction();
                                         return MARIOS_QUEUE_BUSY_OP;
                                 }
                         }
                 }
                 exit_critical_sction();
         }
         return MARIOS_QUEUE_SUCCESS_OP;
 }
enqueue()
mariOS_queue_op_status_t enqueue (mariOS_queue * queue, int8_t * msg, unsigned int size, mariOS_blocking_queue_op_t blocking)
The enqueue function tries to put a message onto the specified \ queue. It takes in input a message and its size (in bytes) and enqueue the message if the queue is not locked for writing operation and if the queue has enough space to contain the message. Whenever these two conditions are not met, the behavior of the function depends on the value of passed.
If MARIOS_BLOCKING_QUEUE_OP is passed and the queue cannot contain the whole message to enqueue, the function suspend the task that will be eventually resumed once the queue has been dequeued by another task. Otherwise, if the queue is just locked for writing operation, the task is simply preempted and will be eventually rescheduled.
If MARIOS_NONBLOCKING_QUEUE_OP is passed, the function will return error conditions related to the condition that impedes the enqueue. Indeed, two possible conditions may happen:
MARIOS_QUEUE_BUSY_OP, which indicates that the queue is blocked for writing operations.
MARIOS_QUEUE_FULL_OP, which indicates that the queue cannot contain the whole message.
Conversely, if the enqueue succeeds, no matter if blocking or not, the function returns MARIOS_QUEUE_SUCCESS_OP.
Parameters
[in,out] queue is the mariOS_queue handler on which the message should be enqueued
[in] msg is the pointer to the message that has to be enqueued
[in] size is the message size (in bytes)
[in] blocking specifies if the enqueue is blocking or not
Returns
operation success or failure
the yield call has no effect since it is invoked inside a critical section! It will eventually have effect once the critical section ends.
Since we are executing a non-blocking enqueue, we return from this function signaling that the queue is full (MARIOS_QUEUE_FULL_OP). Before returning, we must exit from the critical section as well as we must unlock the writing operations on the queue
The yield call has no effect since it is invoked inside a critical section! It will eventually have effect once the critical section ends.
Since we are executing a non-blocking enqueue, we return from this function signaling that the queue is busy (MARIOS_QUEUE_BUSY_OP). Before returning, we must exit from the critical section
Reaching this point implies that the while loop terminates upon the condition writtenFlag != 0, meaning that we successfully enqueued a message
References enter_critical_section(), exit_critical_sction(), queue_t::freeMemory, get_current_task_id(), queue_t::head, MARIOS_BLOCKING_QUEUE_OP, MARIOS_CONFIG_MAX_TASKS, MARIOS_QUEUE_BUSY_OP, MARIOS_QUEUE_FULL_OP, MARIOS_QUEUE_LOCKED, MARIOS_QUEUE_SUCCESS_OP, MARIOS_QUEUE_UNLOCKED, MARIOS_TASK_STATUS_READY, MARIOS_TASK_STATUS_SUSPEND, mariOS_task_yield(), queue_t::queueMemory, set_current_task_status(), set_task_status(), size, queue_t::size, queue_t::tasks_waiting_to_receive, queue_t::tasks_waiting_to_send, and queue_t::wLock.
 {
         int writtenFlag = 0;
         while(0 == writtenFlag) //This flag will be set once the writing is achieved
         {
                 enter_critical_section();
                 {
                         if(MARIOS_QUEUE_UNLOCKED == queue->wLock)
{
                                 queue->wLock = MARIOS_QUEUE_LOCKED;
                                 if(msg_size > queue->freeMemory) //Check available space and yield if no enough space
{
                                         if(MARIOS_BLOCKING_QUEUE_OP == blocking)
{
                                                 queue->tasks_waiting_to_send[get_current_task_id()] = 1;
                                                 set_current_task_status(MARIOS_TASK_STATUS_SUSPEND);
                                                 mariOS_task_yield();
                                         }
                                         else
{
                                                 queue->wLock = MARIOS_QUEUE_UNLOCKED;
                                                 exit_critical_sction();
                                                 return MARIOS_QUEUE_FULL_OP;
                                         }
                                 }
                                 else //Space available
{
                                         if(queue->head+msg_size <= queue->size) //The message just is append
{
                                                 memcpy(queue->queueMemory+queue->head, msg, msg_size);
                                                 queue->head += msg_size;
                                         }
                                         else //We need to split the copy
{
                                                 memcpy(queue->queueMemory+queue->head, msg, queue->size-queue->head);
                                                 memcpy(queue->queueMemory, msg+queue->size-queue->head, msg_size-(queue->size-queue->head));
                                                 queue->head = msg_size-(queue->size-queue->head); //The head just point to the first free location
                                         }
                                         queue->freeMemory -= msg_size;
                                         //Let's make awaken suspended tasks
                                         int i;
                                         for(i = 0; i < MARIOS_CONFIG_MAX_TASKS; i++)
                                                 if(1 == queue->tasks_waiting_to_receive[i])
{
                                                         set_task_status(i, MARIOS_TASK_STATUS_READY);
                                                         queue->tasks_waiting_to_receive[i] = 0;
                                                 }
                                         writtenFlag = 1;
                                 }
                                 queue->wLock = MARIOS_QUEUE_UNLOCKED;
                         }
                         else //The queue is just locked for sending
{
                                 if(MARIOS_BLOCKING_QUEUE_OP == blocking)
{
                                         mariOS_task_yield();
                                 }
                                 else
{
                                         exit_critical_sction();
                                         return MARIOS_QUEUE_BUSY_OP;
                                 }
                         }
                 }
                 exit_critical_sction();
         }
         return MARIOS_QUEUE_SUCCESS_OP;
 }
reset_queue()
void reset_queue (mariOS_queue * queue)
The function restore the queue in a pristine state.
Parameters
[in,out] queue is the queue handler
Return values
None
before continue, we must be sure the queue are not blocked
References queue_t::freeMemory, queue_t::head, MARIOS_CONFIG_MAX_TASKS, MARIOS_QUEUE_UNLOCKED, queue_t::queueMemory, queue_t::rLock, queue_t::size, queue_t::tail, queue_t::tasks_waiting_to_receive, queue_t::tasks_waiting_to_send, and queue_t::wLock.
 {
         if(MARIOS_QUEUE_UNLOCKED == queue->rLock && MARIOS_QUEUE_UNLOCKED == queue->wLock)
         {
                 int i;
                 for(i = 0; i < queue->size; i++)
                         queue->queueMemory[i] = 0;
                 queue->head = 0;
                 queue->tail = 0;
                 queue->freeMemory = queue->size;
                 for(i = 0; i < MARIOS_CONFIG_MAX_TASKS; i++)
                 {
                         queue->tasks_waiting_to_receive[i] = 0;
                         queue->tasks_waiting_to_send[i] = 0;
                 }
         }
 }